//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.People = new HashSet<Person>();
        }
    
        public long city_id { get; set; }
        public string city_name { get; set; }
        public string city_state { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
