//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsageDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.people = new HashSet<person>();
        }
    
        public long city_id { get; set; }
        public string city_name { get; set; }
        public string state { get; set; }
    
        public virtual ICollection<person> people { get; set; }
    }
}
