//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsageDetails
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.EntityClient;

    public partial class DemoUsagePatternsEntities : DbContext
    {
        public DemoUsagePatternsEntities(string conStr)
            : base(conStr)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<city> cities { get; set; }
        public DbSet<electricity_usage> electricity_usage { get; set; }
        public DbSet<month> months { get; set; }
        public DbSet<person> people { get; set; }
        public DbSet<water_usage> water_usage { get; set; }
    }
}
