//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsageDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.electricity_usage = new HashSet<electricity_usage>();
            this.water_usage = new HashSet<water_usage>();
        }
    
        public long person_id { get; set; }
        public string person_name { get; set; }
        public long city_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<electricity_usage> electricity_usage { get; set; }
        public virtual ICollection<water_usage> water_usage { get; set; }
    }
}
