//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterUsageLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class month
    {
        public month()
        {
            this.wusages = new HashSet<wusage>();
        }
    
        public long month_id { get; set; }
        public string mname { get; set; }
        public Nullable<long> year { get; set; }
    
        public virtual ICollection<wusage> wusages { get; set; }
    }
}
