//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterUsageLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class wusage
    {
        public long person_id { get; set; }
        public long wid { get; set; }
        public Nullable<long> day { get; set; }
        public long month_id { get; set; }
        public long w_usage { get; set; }
    
        public virtual month month { get; set; }
        public virtual Person Person { get; set; }
    }
}
